spring:
  profiles:
    active: dev

  # Thymeleaf 설정
    # thymeleaf:
    # cache: false  # 개발 중에는 캐시 끄기 (운영에서는 true)
    # prefix: classpath:/templates/
    # suffix: .html
    # mode: HTML
    # encoding: UTF-8

    # 정적 리소스 설정
    # web:
      # resources:
      # static-locations: classpath:/static/
    # add-mappings: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080